"""Semantic QA for exhibit manifests.

PPTX geometry QA cannot reliably infer that a marker colour matches a legend or
that a jurisdiction classification is backed by the intended evidence. This
module validates the sidecar ``*.exhibits.json`` generated by data-driven
exhibits before or after slide assembly.
"""
from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass
from datetime import date
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ANCHORS = ROOT / "assets" / "maps" / "jurisdiction_anchors.json"


@dataclass
class Finding:
    severity: str
    page: int | str | None
    check: str
    message: str


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, (tuple, set)):
        return list(value)
    return [value]


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_evidence(path: Path | None) -> dict[str, dict[str, Any]]:
    if path is None:
        return {}
    payload = _load_json(path)
    records: dict[str, dict[str, Any]] = {}
    if not isinstance(payload, dict):
        return records
    for section in ("facts", "calculations"):
        for item in payload.get(section, []):
            if not isinstance(item, dict):
                continue
            item_id = str(item.get("id", "")).strip()
            if item_id:
                records[item_id] = item
    return records


def _load_anchor_ids(path: Path) -> set[str]:
    payload = _load_json(path)
    anchors = payload.get("anchors", {}) if isinstance(payload, dict) else {}
    return {str(key) for key in anchors}


def _page(exhibit: dict[str, Any]) -> int | str | None:
    return exhibit.get("page")


def _is_iso_date(value: Any) -> bool:
    try:
        date.fromisoformat(str(value))
        return True
    except ValueError:
        return False


def _evidence_type(record: dict[str, Any]) -> str:
    value = record.get("value")
    if isinstance(value, bool):
        return "qualitative"
    if isinstance(value, (int, float)):
        return "numeric"
    try:
        float(value)
        return "numeric"
    except (TypeError, ValueError):
        return "qualitative"


def validate_categorical_map(
    exhibit: dict[str, Any],
    evidence: dict[str, dict[str, Any]],
    anchor_ids: set[str],
) -> list[Finding]:
    page = _page(exhibit)
    findings: list[Finding] = []

    dimension = str(exhibit.get("classification_dimension", "")).strip()
    if not dimension:
        findings.append(Finding("error", page, "classification_dimension", "Missing classification dimension"))
    caveat = str(exhibit.get("caveat", "")).strip()
    if not caveat:
        findings.append(Finding("error", page, "caveat", "Categorical map requires a visible caveat"))
    if not _is_iso_date(exhibit.get("as_of")):
        findings.append(Finding("error", page, "as_of", "as_of must use ISO YYYY-MM-DD format"))
    if exhibit.get("render_mode") != "svg_base_native_overlay":
        findings.append(Finding("error", page, "render_mode", "Unsupported or missing render mode"))

    categories = exhibit.get("categories")
    jurisdictions = exhibit.get("jurisdictions")
    if not isinstance(categories, list) or not categories:
        findings.append(Finding("error", page, "categories", "At least one category is required"))
        categories = []
    if not isinstance(jurisdictions, list) or not jurisdictions:
        findings.append(Finding("error", page, "jurisdictions", "At least one jurisdiction is required"))
        jurisdictions = []
    if len(categories) > 6:
        findings.append(Finding("error", page, "categories", "Maps support at most six categories"))
    if len(jurisdictions) > 12:
        findings.append(Finding("error", page, "jurisdictions", "Core maps support at most twelve markers"))

    category_ids: set[str] = set()
    for category in categories:
        if not isinstance(category, dict):
            findings.append(Finding("error", page, "categories", "Every category must be a mapping"))
            continue
        category_id = str(category.get("id", "")).strip()
        if not category_id:
            findings.append(Finding("error", page, "categories", "Category id is required"))
        elif category_id in category_ids:
            findings.append(Finding("error", page, "categories", f"Duplicate category id: {category_id}"))
        category_ids.add(category_id)
        if not str(category.get("label", "")).strip():
            findings.append(Finding("error", page, "categories", f"Category {category_id or '<unknown>'} is missing label"))
        if not str(category.get("color", "")).strip():
            findings.append(Finding("error", page, "categories", f"Category {category_id or '<unknown>'} is missing color"))

    usage = {category_id: 0 for category_id in category_ids}
    jurisdiction_ids: set[str] = set()
    custom_anchor_ids = {str(value) for value in _as_list(exhibit.get("custom_anchor_ids"))}
    for jurisdiction in jurisdictions:
        if not isinstance(jurisdiction, dict):
            findings.append(Finding("error", page, "jurisdictions", "Every jurisdiction must be a mapping"))
            continue
        jurisdiction_id = str(jurisdiction.get("id", "")).strip()
        category_id = str(jurisdiction.get("category_id", "")).strip()
        if not jurisdiction_id:
            findings.append(Finding("error", page, "jurisdictions", "Jurisdiction id is required"))
            continue
        if jurisdiction_id in jurisdiction_ids:
            findings.append(Finding("error", page, "jurisdictions", f"Duplicate jurisdiction id: {jurisdiction_id}"))
        jurisdiction_ids.add(jurisdiction_id)
        if category_id not in category_ids:
            findings.append(Finding("error", page, "category_reference", f"{jurisdiction_id} references unknown category: {category_id}"))
        else:
            usage[category_id] += 1
        if not str(jurisdiction.get("label", "")).strip():
            findings.append(Finding("error", page, "jurisdiction_label", f"{jurisdiction_id} is missing label"))
        if not str(jurisdiction.get("note", "")).strip():
            findings.append(Finding("error", page, "jurisdiction_note", f"{jurisdiction_id} is missing note"))

        if jurisdiction_id not in anchor_ids:
            rationale = str(jurisdiction.get("custom_anchor_rationale", "")).strip()
            anchor = jurisdiction.get("anchor")
            if jurisdiction_id not in custom_anchor_ids or not rationale or not isinstance(anchor, dict):
                findings.append(Finding(
                    "error", page, "anchor_registry",
                    f"{jurisdiction_id} is not registered and lacks an approved custom anchor rationale",
                ))
            else:
                findings.append(Finding(
                    "warning", page, "anchor_registry",
                    f"{jurisdiction_id} uses a custom anchor; add it to the registry if reused",
                ))

        entity_type = str(jurisdiction.get("entity_type", "country_or_market"))
        if entity_type == "custom_group" and not _as_list(jurisdiction.get("members")):
            findings.append(Finding("error", page, "entity_scope", f"Custom group {jurisdiction_id} requires members"))

        evidence_ids = [str(value).strip() for value in _as_list(jurisdiction.get("evidence_ids")) if str(value).strip()]
        if not evidence_ids:
            findings.append(Finding("error", page, "evidence_reference", f"{jurisdiction_id} has no evidence IDs"))
        for evidence_id in evidence_ids:
            if evidence and evidence_id not in evidence:
                findings.append(Finding("error", page, "evidence_reference", f"Unknown evidence ID: {evidence_id}"))
                continue
            if evidence_id in evidence:
                evidence_type = _evidence_type(evidence[evidence_id])
                if evidence_type not in {"numeric", "qualitative"}:
                    findings.append(Finding("error", page, "evidence_type", f"Unsupported evidence type for {evidence_id}"))
                used_pages = {str(value) for value in _as_list(evidence[evidence_id].get("used_on_pages"))}
                if page is not None and used_pages and str(page) not in used_pages:
                    findings.append(Finding(
                        "warning", page, "evidence_reference",
                        f"Evidence {evidence_id} does not list page {page} in used_on_pages",
                    ))

    for category_id, count in usage.items():
        if count == 0:
            findings.append(Finding("error", page, "legend_usage", f"Legend category is unused: {category_id}"))

    coverage = exhibit.get("coverage")
    if not isinstance(coverage, dict):
        findings.append(Finding("error", page, "coverage", "Coverage summary is required"))
    else:
        try:
            reviewed = int(coverage.get("reviewed"))
            shown = int(coverage.get("shown"))
            if shown != len(jurisdictions):
                findings.append(Finding("error", page, "coverage", "coverage.shown must equal jurisdiction count"))
            if reviewed < shown:
                findings.append(Finding("error", page, "coverage", "coverage.reviewed cannot be below coverage.shown"))
        except (TypeError, ValueError):
            findings.append(Finding("error", page, "coverage", "Coverage reviewed/shown must be integers"))

    if not exhibit.get("mutually_exclusive", True):
        findings.append(Finding(
            "warning", page, "classification_model",
            "Non-exclusive classifications are usually better shown as a matrix or heatmap",
        ))
    return findings


def run_qa(
    manifest_path: Path,
    evidence_path: Path | None = None,
    anchor_registry_path: Path = DEFAULT_ANCHORS,
) -> list[Finding]:
    payload = _load_json(manifest_path)
    if isinstance(payload, list):
        exhibits = payload
    elif isinstance(payload, dict):
        exhibits = payload.get("exhibits", [])
    else:
        return [Finding("error", None, "manifest", "Manifest must be a list or an object with exhibits")]
    if not isinstance(exhibits, list) or not exhibits:
        return [Finding("error", None, "manifest", "No exhibits found")]

    evidence = _load_evidence(evidence_path)
    anchor_ids = _load_anchor_ids(anchor_registry_path)
    findings: list[Finding] = []
    for exhibit in exhibits:
        if not isinstance(exhibit, dict):
            findings.append(Finding("error", None, "manifest", "Every exhibit must be a mapping"))
            continue
        exhibit_type = str(exhibit.get("type", "")).strip()
        if exhibit_type == "categorical_jurisdiction_map":
            findings.extend(validate_categorical_map(exhibit, evidence, anchor_ids))
        elif not exhibit_type:
            findings.append(Finding("error", _page(exhibit), "exhibit_type", "Exhibit type is required"))
        else:
            findings.append(Finding("warning", _page(exhibit), "exhibit_type", f"No semantic QA registered for {exhibit_type}"))
    return findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate semantic exhibit manifests")
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--facts", type=Path, default=None, help="Optional evidence.json")
    parser.add_argument("--anchors", type=Path, default=DEFAULT_ANCHORS)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--fail-on-warning", action="store_true")
    args = parser.parse_args(argv)

    findings = run_qa(args.manifest, args.facts, args.anchors)
    if args.json:
        print(json.dumps([asdict(item) for item in findings], ensure_ascii=False, indent=2))
    else:
        for item in findings:
            where = f"page {item.page}" if item.page is not None else "deck"
            print(f"[{item.severity}] {where} {item.check}: {item.message}")
    if any(item.severity == "error" for item in findings):
        return 1
    if args.fail_on_warning and findings:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
